// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var msTablesIp = MsTablesIp.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class MsTablesIp
    {
        [JsonProperty("REF_ID")]
        public long RefId { get; set; }

        [JsonProperty("TABLE_CODE")]
        public string TableCode { get; set; }

        [JsonProperty("TABLE_TYPE")]
        public long TableType { get; set; }

        [JsonProperty("IP_CODE")]
        public string IpCode { get; set; }

        [JsonProperty("TABLEIPCODE")]
        public string Tableipcode { get; set; }

        [JsonProperty("IP_TYPE")]
        public long IpType { get; set; }

        [JsonProperty("IP_CAPTION")]
        public string IpCaption { get; set; }

        [JsonProperty("IP_SELECT_SQL")]
        public string IpSelectSql { get; set; }

        [JsonProperty("IP_WHERE_SQL")]
        public object IpWhereSql { get; set; }

        [JsonProperty("IP_ORDER_BY")]
        public object IpOrderBy { get; set; }

        [JsonProperty("EXTERNAL_IP_CODE")]
        public object ExternalIpCode { get; set; }

        [JsonProperty("VIEW_CMP_TYPE")]
        public long ViewCmpType { get; set; }

        [JsonProperty("CMP_PROPERTIES")]
        public object CmpProperties { get; set; }

        [JsonProperty("NAVIGATOR")]
        public string Navigator { get; set; }

        [JsonProperty("DATA_READ")]
        public long DataRead { get; set; }

        [JsonProperty("FIND_FNAME")]
        public object FindFname { get; set; }

        [JsonProperty("DATA_FIND")]
        public long DataFind { get; set; }

        [JsonProperty("AUTO_INSERT")]
        public bool AutoInsert { get; set; }

        [JsonProperty("MASTER_TABLEIPCODE")]
        public object MasterTableipcode { get; set; }

        [JsonProperty("MASTER_TABLE_NAME")]
        public object MasterTableName { get; set; }

        [JsonProperty("MASTER_KEY_FNAME")]
        public object MasterKeyFname { get; set; }

        [JsonProperty("PROP_SUBVIEW")]
        public object PropSubview { get; set; }

        [JsonProperty("PROP_JOINTABLE")]
        public object PropJointable { get; set; }

        [JsonProperty("PROP_VIEWS")]
        public string PropViews { get; set; }

        [JsonProperty("PROP_NAVIGATOR")]
        public object PropNavigator { get; set; }

        [JsonProperty("PROP_SEARCH")]
        public object PropSearch { get; set; }

        [JsonProperty("SOFTWARE_CODE")]
        public string SoftwareCode { get; set; }

        [JsonProperty("PROJECT_CODE")]
        public string ProjectCode { get; set; }

        [JsonProperty("LKP_SCHEMAS_CODE")]
        public object LkpSchemasCode { get; set; }

        [JsonProperty("LKP_DBASE_TYPE")]
        public long LkpDbaseType { get; set; }

        [JsonProperty("LKP_MODUL_CODE")]
        public string LkpModulCode { get; set; }

        [JsonProperty("LKP_TABLE_CODE")]
        public string LkpTableCode { get; set; }

        [JsonProperty("LKP_TABLE_NAME")]
        public string LkpTableName { get; set; }

        [JsonProperty("LKP_KEY_FNAME")]
        public string LkpKeyFname { get; set; }

        [JsonProperty("LKP_TABLE_TYPE")]
        public long LkpTableType { get; set; }

        [JsonProperty("LKP_MASTER_TABLEIPCODE")]
        public object LkpMasterTableipcode { get; set; }

        [JsonProperty("LKP_MASTER_TABLE_NAME")]
        public object LkpMasterTableName { get; set; }

        [JsonProperty("LKP_MASTER_KEY_FNAME")]
        public object LkpMasterKeyFname { get; set; }

        [JsonProperty("LKP_TB_CAPTION")]
        public string LkpTbCaption { get; set; }

        [JsonProperty("LKP_TB_SELECT_SQL")]
        public object LkpTbSelectSql { get; set; }

        [JsonProperty("LKP_TB_WHERE_SQL")]
        public object LkpTbWhereSql { get; set; }

        [JsonProperty("LKP_TB_ORDER_BY")]
        public object LkpTbOrderBy { get; set; }

        [JsonProperty("LKP_PROP_SUBVIEW")]
        public object LkpPropSubview { get; set; }

        [JsonProperty("LKP_PROP_JOINTABLE")]
        public object LkpPropJointable { get; set; }
    }

    public partial class MsTablesIp
    {
        public static MsTablesIp[] FromJson(string json) => JsonConvert.DeserializeObject<MsTablesIp[]>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this MsTablesIp[] self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
